/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.dialog;

/**
 *
 * @author SunCho
 */
public class About extends javax.swing.JDialog {

    /**
     * Creates new form About
     * @param parent
     * @param modal
     */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Info = new javax.swing.JPanel();
        jLb_Close = new javax.swing.JLabel();
        jLb_Icon = new javax.swing.JLabel();
        jLb_Name = new javax.swing.JLabel();
        jLb_Version = new javax.swing.JLabel();
        jLb_Group = new javax.swing.JLabel();
        jLb_Author = new javax.swing.JLabel();
        jLb_Member1 = new javax.swing.JLabel();
        jLb_Member2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel_Info.setBackground(new java.awt.Color(42, 150, 83));
        jPanel_Info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 212, 212)));

        jLb_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_20px.png"))); // NOI18N
        jLb_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLb_CloseMouseClicked(evt);
            }
        });

        jLb_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Info_96px.png"))); // NOI18N

        jLb_Name.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLb_Name.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Name.setText("DOManagement");

        jLb_Version.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLb_Version.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Version.setText("Version: 1.1");

        jLb_Group.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLb_Group.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Group.setText("Group: SunCho");

        jLb_Author.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLb_Author.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Author.setText("Member:");

        jLb_Member1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLb_Member1.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Member1.setText("Number 1");

        jLb_Member2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLb_Member2.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Member2.setText("Number 2");

        javax.swing.GroupLayout jPanel_InfoLayout = new javax.swing.GroupLayout(jPanel_Info);
        jPanel_Info.setLayout(jPanel_InfoLayout);
        jPanel_InfoLayout.setHorizontalGroup(
            jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLb_Icon)
                .addGap(37, 37, 37)
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLb_Name)
                    .addComponent(jLb_Version)
                    .addComponent(jLb_Group)
                    .addGroup(jPanel_InfoLayout.createSequentialGroup()
                        .addComponent(jLb_Author)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLb_Member2)
                            .addComponent(jLb_Member1))))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLb_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel_InfoLayout.setVerticalGroup(
            jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLb_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_InfoLayout.createSequentialGroup()
                        .addComponent(jLb_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLb_Version)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLb_Group)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLb_Author)
                            .addComponent(jLb_Member1)))
                    .addComponent(jLb_Icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLb_Member2)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLb_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_CloseMouseClicked
        this.dispose();
        //System.exit(0);
    }//GEN-LAST:event_jLb_CloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            About dialog = new About(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLb_Author;
    private javax.swing.JLabel jLb_Close;
    private javax.swing.JLabel jLb_Group;
    private javax.swing.JLabel jLb_Icon;
    private javax.swing.JLabel jLb_Member1;
    private javax.swing.JLabel jLb_Member2;
    private javax.swing.JLabel jLb_Name;
    private javax.swing.JLabel jLb_Version;
    private javax.swing.JPanel jPanel_Info;
    // End of variables declaration//GEN-END:variables
}
