/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.dialog;

import Function.OpenForm;
import Gui.SignIn;
import Model.StudentModel;
import Model.TransferRoomModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SunCho
 */
public class ReportAction extends javax.swing.JDialog {

    private static int reportId = -1;
    private static int roomId = -1;
    private static int studentId = -1;
    private static int check = -1;

    TransferRoomModel trm = new TransferRoomModel();
    StudentModel sm = new StudentModel();

    /**
     * Creates new form ReportAction
     * @param parent
     * @param modal
     * @param reportId
     * @param roomId
     * @param studentId
     * @param check
     */
    public ReportAction(java.awt.Frame parent, boolean modal, int reportId, int roomId, int studentId, int check) {
        super(parent, modal);
        initComponents();
        ReportAction.reportId = reportId;
        ReportAction.roomId = roomId;
        ReportAction.studentId = studentId;

        if (check == 1) {
            jPanel_Btn_Action.setVisible(false);
            jLb_Description.setText("Do you want delete report?");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLb_Close = new javax.swing.JLabel();
        jLb_AccountInfo = new javax.swing.JLabel();
        jLb_Description = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel_Btn_Action = new javax.swing.JPanel();
        jLb_Btn_Action = new javax.swing.JLabel();
        jPanel_Btn_Delete = new javax.swing.JPanel();
        jLb_Btn_Delete = new javax.swing.JLabel();
        jPanel_Btn_Delete1 = new javax.swing.JPanel();
        jLb_Btn_Delete1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(42, 150, 83));
        jPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 212, 212)));

        jLb_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_20px.png"))); // NOI18N
        jLb_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLb_CloseMouseClicked(evt);
            }
        });

        jLb_AccountInfo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLb_AccountInfo.setForeground(new java.awt.Color(255, 255, 255));
        jLb_AccountInfo.setText("Action");

        jLb_Description.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLb_Description.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Description.setText("What do you want to do?");

        jSeparator1.setBackground(new java.awt.Color(42, 150, 83));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel_Btn_Action.setBackground(new java.awt.Color(42, 150, 83));
        jPanel_Btn_Action.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_Btn_Action.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Btn_Action.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_Btn_ActionMouseClicked(evt);
            }
        });

        jLb_Btn_Action.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLb_Btn_Action.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Btn_Action.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_Btn_Action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Checked_20px.png"))); // NOI18N
        jLb_Btn_Action.setText("Approval");

        javax.swing.GroupLayout jPanel_Btn_ActionLayout = new javax.swing.GroupLayout(jPanel_Btn_Action);
        jPanel_Btn_Action.setLayout(jPanel_Btn_ActionLayout);
        jPanel_Btn_ActionLayout.setHorizontalGroup(
            jPanel_Btn_ActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Btn_ActionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLb_Btn_Action, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Btn_ActionLayout.setVerticalGroup(
            jPanel_Btn_ActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Btn_ActionLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLb_Btn_Action)
                .addGap(5, 5, 5))
        );

        jPanel_Btn_Delete.setBackground(new java.awt.Color(42, 150, 83));
        jPanel_Btn_Delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_Btn_Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Btn_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_Btn_DeleteMouseClicked(evt);
            }
        });

        jLb_Btn_Delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLb_Btn_Delete.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Btn_Delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_Btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Unavailable_20px.png"))); // NOI18N
        jLb_Btn_Delete.setText("Delete");

        javax.swing.GroupLayout jPanel_Btn_DeleteLayout = new javax.swing.GroupLayout(jPanel_Btn_Delete);
        jPanel_Btn_Delete.setLayout(jPanel_Btn_DeleteLayout);
        jPanel_Btn_DeleteLayout.setHorizontalGroup(
            jPanel_Btn_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Btn_DeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLb_Btn_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Btn_DeleteLayout.setVerticalGroup(
            jPanel_Btn_DeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Btn_DeleteLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLb_Btn_Delete)
                .addGap(5, 5, 5))
        );

        jPanel_Btn_Delete1.setBackground(new java.awt.Color(42, 150, 83));
        jPanel_Btn_Delete1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_Btn_Delete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Btn_Delete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_Btn_Delete1MouseClicked(evt);
            }
        });

        jLb_Btn_Delete1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLb_Btn_Delete1.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Btn_Delete1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_Btn_Delete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_20px.png"))); // NOI18N
        jLb_Btn_Delete1.setText("Close");

        javax.swing.GroupLayout jPanel_Btn_Delete1Layout = new javax.swing.GroupLayout(jPanel_Btn_Delete1);
        jPanel_Btn_Delete1.setLayout(jPanel_Btn_Delete1Layout);
        jPanel_Btn_Delete1Layout.setHorizontalGroup(
            jPanel_Btn_Delete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Btn_Delete1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLb_Btn_Delete1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Btn_Delete1Layout.setVerticalGroup(
            jPanel_Btn_Delete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Btn_Delete1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLb_Btn_Delete1)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLb_Close)
                .addGap(8, 8, 8))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jPanel_Btn_Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel_Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel_Btn_Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLb_Description)
                        .addGroup(jPanelLayout.createSequentialGroup()
                            .addComponent(jLb_AccountInfo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLb_Close)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLb_AccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLb_Description)
                .addGap(20, 20, 20)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Btn_Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Btn_Delete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLb_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLb_CloseMouseClicked

    private void jPanel_Btn_ActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Btn_ActionMouseClicked
        boolean isCheck1 = trm.updateTransferRoom(true, reportId);
        boolean isCheck2 = sm.updateRoomId(roomId, studentId);
        if (isCheck1 && isCheck2) {
            trm.deleteTransferRoom(studentId, false);
            this.dispose();
        }
    }//GEN-LAST:event_jPanel_Btn_ActionMouseClicked

    private void jPanel_Btn_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Btn_DeleteMouseClicked
        int i = JOptionPane.showConfirmDialog(null, "Are you sure?", " Notification",
            JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE,
            new javax.swing.ImageIcon(getClass().getResource("/Images/Help_40px.png")));

        if(i==0){
            boolean isCheck = trm.deleteTransferRoomById(reportId);
            if (isCheck) {
                this.dispose();
            }
        }
    }//GEN-LAST:event_jPanel_Btn_DeleteMouseClicked

    private void jPanel_Btn_Delete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Btn_Delete1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jPanel_Btn_Delete1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        if (reportId == -1) {
            SignIn signin = new SignIn();
            OpenForm.Open(signin);
        } else {
            java.awt.EventQueue.invokeLater(() -> {
                ReportAction dialog = new ReportAction(new javax.swing.JFrame(), true, -1, -1, -1, -1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLb_AccountInfo;
    private javax.swing.JLabel jLb_Btn_Action;
    private javax.swing.JLabel jLb_Btn_Delete;
    private javax.swing.JLabel jLb_Btn_Delete1;
    private javax.swing.JLabel jLb_Close;
    private javax.swing.JLabel jLb_Description;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel_Btn_Action;
    private javax.swing.JPanel jPanel_Btn_Delete;
    private javax.swing.JPanel jPanel_Btn_Delete1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
