/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.dialog;

import Function.OpenForm;
import Function.RoomDetailController;
import Gui.SignIn;
import Model.RoomModel;
import Model.StudentModel;
import Object.Room;
import Object.Student;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author SunCho
 */
public class RoomInfo extends javax.swing.JDialog {
    
    StudentModel sm = new StudentModel();
    RoomModel rm = new RoomModel();
    RoomDetailController rdc = new RoomDetailController();
    
    private static Room roomDetails = null;
    
    /**
     * Creates new form RoomInfo
     *
     * @param parent
     * @param modal
     * @param room
     */
    public RoomInfo(java.awt.Frame parent, boolean modal, Room room) {
        super(parent, modal);
        initComponents();
        setStyleTable();
        RoomInfo.roomDetails = room;
        loadRoomInfo(roomDetails);       
        loadListMember();
        jLb_Notification.setText("");
    }
    
    private void setStyleTable(){
        Font f = new Font("Segoe UI", Font.PLAIN, 13);
        jTable_ListMember.getTableHeader().setFont(f);
    }
    
    private void loadRoomInfo(Room roomDetails){
        jLb_RoomNo.setText(roomDetails.getRoomNumber());
        jCb_Status.setSelectedIndex(roomDetails.getStatus());
        int isPay = 0;
        if(roomDetails.isPaystatus() == true){
            isPay = 1;
        }
        jCb_PaymentStatus.setSelectedIndex(isPay);
        jLb_TotalSlot.setText(roomDetails.getNumberStudent() + roomDetails.getFreeSlot() + "");
        jLb_NumberOfStudents.setText(" " + roomDetails.getNumberStudent());
        jLb_FreeSlot.setText(roomDetails.getFreeSlot() + "");
        jLb_ElectricityOld.setText(roomDetails.getElectricityNumberLastSemester() + "");
        jTF_ElectricityNew.setText(" " + roomDetails.getElectricityNumberThisSemester());
        int totalElectricity = roomDetails.getElectricityNumberThisSemester() - roomDetails.getElectricityNumberLastSemester();
        jLb_ElectricityUsed.setText(totalElectricity + "");
        jLb_WaterOld.setText(roomDetails.getWaterNumberLastSemester() + "");
        jTF_WaterNew.setText(" " + roomDetails.getWaterNumberThisSemester());
        int totalWater = roomDetails.getWaterNumberThisSemester() - roomDetails.getWaterNumberLastSemester();
        jLb_WaterUsed.setText(totalWater + "");
    }
    
    private void loadListMember(){
        List<Student> listStudent = new ArrayList();
        listStudent = sm.getStudentsByRoom(roomDetails.getId());        
        rdc.displayListMember(jTable_ListMember, listStudent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel = new javax.swing.JPanel();
        jLb_Close = new javax.swing.JLabel();
        jLb_RoomInfo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLb_RoomNo = new javax.swing.JLabel();
        jCb_Status = new javax.swing.JComboBox<>();
        jCb_PaymentStatus = new javax.swing.JComboBox<>();
        jLb_TotalSlot = new javax.swing.JLabel();
        jLb_NumberOfStudents = new javax.swing.JLabel();
        jLb_FreeSlot = new javax.swing.JLabel();
        jLb_ElectricityOld = new javax.swing.JLabel();
        jTF_ElectricityNew = new javax.swing.JTextField();
        jLb_ElectricityUsed = new javax.swing.JLabel();
        jLb_WaterOld = new javax.swing.JLabel();
        jTF_WaterNew = new javax.swing.JTextField();
        jLb_WaterUsed = new javax.swing.JLabel();
        jLb_Notification = new javax.swing.JLabel();
        jLb_ListMember = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ListMember = new javax.swing.JTable();
        jPanel_Btn_Update = new javax.swing.JPanel();
        jLb_Btn_Action = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel_Btn_Close = new javax.swing.JPanel();
        jLb_Btn_Delete = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(42, 150, 83));
        jPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 212, 212)));

        jLb_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_20px.png"))); // NOI18N
        jLb_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLb_CloseMouseClicked(evt);
            }
        });

        jLb_RoomInfo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLb_RoomInfo.setForeground(new java.awt.Color(255, 255, 255));
        jLb_RoomInfo.setText("Room Info");

        jSeparator1.setBackground(new java.awt.Color(42, 150, 83));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Room No:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Status:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payment status:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total slot:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number of students:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Free slot:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Number of Electricity (old):");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Number of Electricity (new):");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Number electricity used:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Number of Water (old):");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Number of Water (new):");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Number water used:");

        jLb_RoomNo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLb_RoomNo.setForeground(new java.awt.Color(255, 255, 255));
        jLb_RoomNo.setText("Null");

        jCb_Status.setBackground(new java.awt.Color(42, 150, 83));
        jCb_Status.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jCb_Status.setForeground(new java.awt.Color(0, 102, 51));
        jCb_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Deactive", " Active", " Maintenance" }));
        jCb_Status.setBorder(null);

        jCb_PaymentStatus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jCb_PaymentStatus.setForeground(new java.awt.Color(0, 102, 51));
        jCb_PaymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Not yet", " Done" }));
        jCb_PaymentStatus.setBorder(null);

        jLb_TotalSlot.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLb_TotalSlot.setForeground(new java.awt.Color(255, 255, 255));
        jLb_TotalSlot.setText("Null");

        jLb_NumberOfStudents.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLb_NumberOfStudents.setForeground(new java.awt.Color(255, 255, 255));
        jLb_NumberOfStudents.setText("Null");

        jLb_FreeSlot.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLb_FreeSlot.setForeground(new java.awt.Color(255, 255, 255));
        jLb_FreeSlot.setText("Null");

        jLb_ElectricityOld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLb_ElectricityOld.setForeground(new java.awt.Color(255, 255, 255));
        jLb_ElectricityOld.setText("Null");

        jTF_ElectricityNew.setBackground(new java.awt.Color(42, 150, 83));
        jTF_ElectricityNew.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTF_ElectricityNew.setForeground(new java.awt.Color(255, 255, 255));
        jTF_ElectricityNew.setText(" 500");
        jTF_ElectricityNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTF_ElectricityNew.setCaretColor(new java.awt.Color(255, 255, 255));

        jLb_ElectricityUsed.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLb_ElectricityUsed.setForeground(new java.awt.Color(255, 255, 255));
        jLb_ElectricityUsed.setText("Null");

        jLb_WaterOld.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLb_WaterOld.setForeground(new java.awt.Color(255, 255, 255));
        jLb_WaterOld.setText("Null");

        jTF_WaterNew.setBackground(new java.awt.Color(42, 150, 83));
        jTF_WaterNew.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTF_WaterNew.setForeground(new java.awt.Color(255, 255, 255));
        jTF_WaterNew.setText(" 444");
        jTF_WaterNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTF_WaterNew.setCaretColor(new java.awt.Color(255, 255, 255));

        jLb_WaterUsed.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLb_WaterUsed.setForeground(new java.awt.Color(255, 255, 255));
        jLb_WaterUsed.setText("Null");

        jLb_Notification.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLb_Notification.setForeground(new java.awt.Color(102, 255, 204));
        jLb_Notification.setText("Update room info successfuly !");

        jLb_ListMember.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLb_ListMember.setForeground(new java.awt.Color(255, 255, 255));
        jLb_ListMember.setText("List member");

        jSeparator2.setBackground(new java.awt.Color(42, 150, 83));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jTable_ListMember.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTable_ListMember.setForeground(new java.awt.Color(51, 51, 51));
        jTable_ListMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Fullname", "Roll Number", "Email", "Phone Number", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_ListMember.setGridColor(new java.awt.Color(204, 204, 204));
        jTable_ListMember.setRowHeight(25);
        jTable_ListMember.setSelectionBackground(new java.awt.Color(45, 180, 95));
        jScrollPane2.setViewportView(jTable_ListMember);
        if (jTable_ListMember.getColumnModel().getColumnCount() > 0) {
            jTable_ListMember.getColumnModel().getColumn(0).setMinWidth(50);
            jTable_ListMember.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel_Btn_Update.setBackground(new java.awt.Color(42, 150, 83));
        jPanel_Btn_Update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_Btn_Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Btn_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_Btn_UpdateMouseClicked(evt);
            }
        });

        jLb_Btn_Action.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLb_Btn_Action.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Btn_Action.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_Btn_Action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Checkmark_20px.png"))); // NOI18N
        jLb_Btn_Action.setText("Update");

        javax.swing.GroupLayout jPanel_Btn_UpdateLayout = new javax.swing.GroupLayout(jPanel_Btn_Update);
        jPanel_Btn_Update.setLayout(jPanel_Btn_UpdateLayout);
        jPanel_Btn_UpdateLayout.setHorizontalGroup(
            jPanel_Btn_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Btn_UpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLb_Btn_Action, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Btn_UpdateLayout.setVerticalGroup(
            jPanel_Btn_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Btn_UpdateLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLb_Btn_Action)
                .addGap(5, 5, 5))
        );

        jSeparator3.setBackground(new java.awt.Color(42, 150, 83));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel_Btn_Close.setBackground(new java.awt.Color(42, 150, 83));
        jPanel_Btn_Close.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel_Btn_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Btn_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_Btn_CloseMouseClicked(evt);
            }
        });

        jLb_Btn_Delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLb_Btn_Delete.setForeground(new java.awt.Color(255, 255, 255));
        jLb_Btn_Delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_Btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close_20px.png"))); // NOI18N
        jLb_Btn_Delete.setText("Close");

        javax.swing.GroupLayout jPanel_Btn_CloseLayout = new javax.swing.GroupLayout(jPanel_Btn_Close);
        jPanel_Btn_Close.setLayout(jPanel_Btn_CloseLayout);
        jPanel_Btn_CloseLayout.setHorizontalGroup(
            jPanel_Btn_CloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Btn_CloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLb_Btn_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Btn_CloseLayout.setVerticalGroup(
            jPanel_Btn_CloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Btn_CloseLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLb_Btn_Delete)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addGap(132, 132, 132)
                        .addComponent(jLb_RoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addGap(161, 161, 161)
                        .addComponent(jCb_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)
                        .addGap(78, 78, 78)
                        .addComponent(jCb_PaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(jLb_TotalSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)
                        .addGap(70, 70, 70)
                        .addComponent(jLb_NumberOfStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6)
                        .addGap(121, 121, 121)
                        .addComponent(jLb_FreeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel7)
                        .addGap(20, 20, 20)
                        .addComponent(jLb_ElectricityOld, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8)
                        .addGap(20, 20, 20)
                        .addComponent(jTF_ElectricityNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel9)
                        .addGap(20, 20, 20)
                        .addComponent(jLb_ElectricityUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLb_ListMember)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(807, 807, 807)
                                .addComponent(jPanel_Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(44, 44, 44)
                                .addComponent(jLb_WaterOld, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel11)
                                .addGap(44, 44, 44)
                                .addComponent(jTF_WaterNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel12)
                                .addGap(47, 47, 47)
                                .addComponent(jLb_WaterUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLb_Notification, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel_Btn_Close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLb_RoomInfo)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLb_Close)
                        .addGap(8, 8, 8))))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLb_RoomInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLb_Close)
                        .addGap(21, 21, 21)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCb_PaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_RoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCb_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_TotalSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_FreeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_NumberOfStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_ElectricityOld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_ElectricityNew, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_ElectricityUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_WaterNew, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_WaterOld, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_WaterUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jPanel_Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLb_ListMember, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Btn_Close, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_Notification, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_Btn_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Btn_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jPanel_Btn_CloseMouseClicked

    private void jPanel_Btn_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Btn_UpdateMouseClicked
        int electricityNumber = Integer.parseInt(jTF_ElectricityNew.getText().trim());
        if(electricityNumber == roomDetails.getElectricityNumberThisSemester()){
            electricityNumber = 0;            
        }
        
        int waterNumber = Integer.parseInt(jTF_WaterNew.getText().trim());
        if(waterNumber == roomDetails.getWaterNumberThisSemester()){
            waterNumber = 0;
        }
   
        boolean payStatus = false;
        if(jCb_PaymentStatus.getSelectedIndex() == 1){
            payStatus = true;
        }
        int status = jCb_Status.getSelectedIndex();
        int roomId = roomDetails.getId();
        
        boolean isCheck = false;
        isCheck = rm.updateRoomFromModalRoomDetails(electricityNumber, waterNumber, payStatus, status, roomId);
        
        if(isCheck){
            RoomInfo.roomDetails = rm.getRoomById(roomId);
            loadRoomInfo(RoomInfo.roomDetails);
            jLb_Notification.setText("Update room info successfuly !");
        }
    }//GEN-LAST:event_jPanel_Btn_UpdateMouseClicked

    private void jLb_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLb_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLb_CloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        if(roomDetails == null){
            SignIn signin = new SignIn();
            OpenForm.Open(signin);
        }else{
            java.awt.EventQueue.invokeLater(() -> {
                RoomInfo dialog = new RoomInfo(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCb_PaymentStatus;
    private javax.swing.JComboBox<String> jCb_Status;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLb_Btn_Action;
    private javax.swing.JLabel jLb_Btn_Delete;
    private javax.swing.JLabel jLb_Close;
    private javax.swing.JLabel jLb_ElectricityOld;
    private javax.swing.JLabel jLb_ElectricityUsed;
    private javax.swing.JLabel jLb_FreeSlot;
    private javax.swing.JLabel jLb_ListMember;
    private javax.swing.JLabel jLb_Notification;
    private javax.swing.JLabel jLb_NumberOfStudents;
    private javax.swing.JLabel jLb_RoomInfo;
    private javax.swing.JLabel jLb_RoomNo;
    private javax.swing.JLabel jLb_TotalSlot;
    private javax.swing.JLabel jLb_WaterOld;
    private javax.swing.JLabel jLb_WaterUsed;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel_Btn_Close;
    private javax.swing.JPanel jPanel_Btn_Update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTF_ElectricityNew;
    private javax.swing.JTextField jTF_WaterNew;
    private javax.swing.JTable jTable_ListMember;
    // End of variables declaration//GEN-END:variables
}
